- direction: GZ_TO_ROS
  gz_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
- direction: GZ_TO_ROS
  gz_topic_name: /model/robot_0/odometry
  gz_type_name: gz.msgs.Odometry
  ros_topic_name: /robot_0/odom
  ros_type_name: nav_msgs/msg/Odometry
- direction: GZ_TO_ROS
  gz_topic_name: /model/robot_0/tf
  gz_type_name: gz.msgs.Pose_V
  ros_topic_name: /tf
  ros_type_name: tf2_msgs/msg/TFMessage
- direction: ROS_TO_GZ
  gz_topic_name: /model/robot_0/cmd_vel
  gz_type_name: gz.msgs.Twist
  ros_topic_name: /robot_0/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
- direction: GZ_TO_ROS
  gz_topic_name: /robot_0/camara
  gz_type_name: gz.msgs.Image
  ros_topic_name: /robot_0/cameraImagen/image_raw
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /robot_0/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_topic_name: /robot_0/cameraImagen/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
- direction: GZ_TO_ROS
  gz_topic_name: /robot_0/lidar
  gz_type_name: gz.msgs.LaserScan
  ros_topic_name: /robot_0/laser
  ros_type_name: sensor_msgs/msg/LaserScan
- direction: GZ_TO_ROS
  gz_topic_name: /world/robot_world/model/robot_0/joint_state
  gz_type_name: gz.msgs.Model
  ros_topic_name: /robot_0/joint_states
  ros_type_name: sensor_msgs/msg/JointState
- direction: GZ_TO_ROS
  gz_topic_name: /model/robot_1/odometry
  gz_type_name: gz.msgs.Odometry
  ros_topic_name: /robot_1/odom
  ros_type_name: nav_msgs/msg/Odometry
- direction: GZ_TO_ROS
  gz_topic_name: /model/robot_1/tf
  gz_type_name: gz.msgs.Pose_V
  ros_topic_name: /tf
  ros_type_name: tf2_msgs/msg/TFMessage
- direction: ROS_TO_GZ
  gz_topic_name: /model/robot_1/cmd_vel
  gz_type_name: gz.msgs.Twist
  ros_topic_name: /robot_1/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
- direction: GZ_TO_ROS
  gz_topic_name: /robot_1/camara
  gz_type_name: gz.msgs.Image
  ros_topic_name: /robot_1/cameraImagen/image_raw
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /robot_1/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_topic_name: /robot_1/cameraImagen/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
- direction: GZ_TO_ROS
  gz_topic_name: /robot_1/lidar
  gz_type_name: gz.msgs.LaserScan
  ros_topic_name: /robot_1/laser
  ros_type_name: sensor_msgs/msg/LaserScan
- direction: GZ_TO_ROS
  gz_topic_name: /world/robot_world/model/robot_1/joint_state
  gz_type_name: gz.msgs.Model
  ros_topic_name: /robot_1/joint_states
  ros_type_name: sensor_msgs/msg/JointState
